# This file configures the  app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basedmatch-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basedmatch
  template:
    metadata:
      labels:
        app: basedmatch
    spec:
      containers:
      - name: basedmatch-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/aiot-fit-xlab/basedmatch-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"